function main(splash,args)
    splash:go(args.url)
    splash:wait(0.2)
    splash:runjs("document.querySelector('#username').value = '21013078'")
    splash:runjs("document.querySelector('#password').value = 'sHl5743866'")
    splash:wait(0.1)
    splash:runjs("document.querySelector('button.auth_login_btn').click()")
    splash:wait(2)
    splash:go("https://i.s.ecust.edu.cn/space/index")
    splash:wait(0.2)
    splash:runjs("window.location = document.querySelector('iframe').src")
    splash:wait(0.5)
    splash:runjs("document.querySelectorAll('.mic_select1>.mic_select_list>li')[10].click()")
    splash:wait(1)
    splash:runjs("document.querySelectorAll(' div.wzy_couros > ul > li')[0].click()")
    splash:wait(5)
    return splash:png()
end
